### ISSUE TITLE
Radar issue returns when using interface mods (GTA III and GTA VC)

### ISSUE THREAD

**Issue by ghost** [CookiePLMonster/SilentPatch#107] opened 2024-11-10 06:19 UTC
This mod finally fixed the radar position in GTA III and Vice City but when using interface mods, such as Remastered HUD Interface for Vice City, the radar gap returns, so I hope you fix the issue. This comparison below is an example:

Without Interface mods:

![Screenshot (124)](https://github.com/user-attachments/assets/2c516563-3651-4180-aad6-311285f8636c)

After Adding Interface mods (in this case I am using the "Remastered HUD Interface" mod:

![Screenshot (123)](https://github.com/user-attachments/assets/a4322f29-f525-4e48-a19f-958b312315c7)

I hope you look into it and fix the compatiblity issue

**Comment by CookiePLMonster** [comment] 2024-11-10 08:09
There is nothing I can do here, this mod is simply authored incorrectly and its radar disc is too small. In fact, because SP enlarges the disc I half expect this issue to manifest with this texture even without the patch.

**Comment by ghost** [comment] 2024-11-11 14:24
Ok thanks, maybe you're right. By the way, I am about to walkthrough GTA III, Vice City and San Andreas using Zolika1351's Chaos Mod (it's usually called ZChaos) I hope that this update is compatible with the chaos mod. And something else, you've to update your GInput mod, because I have a minor visual problem with it, few months ago when I was doing the final mission in GTA Vice City, the first letter of the word "safe" text where it says "The Mafia is stealing your money, defend the safe" is overrided with gamepad icon. Something like this:

![Screenshot (125)](https://github.com/user-attachments/assets/22e67216-8bab-4c84-b337-ebcc5d659ca2)

I hope you look into this issue and hopefully try to fix it.

**Comment by CookiePLMonster** [comment] 2024-11-11 16:51
This GXT text uses an invalid color code. If GInput ever gets an update it'll be fixed, for now it's the only text in the game to use that code.

**Comment by ghost** [comment] 2024-11-11 17:08
Ok man, thanks.

**Comment by CookiePLMonster** [comment] 2024-11-12 10:40
As for the radar size, the disc has been shrunk by 2px (units) as otherwise gaps on the **inside** appeared (like they do on VC Xbox!). Can you share a link to this UI mod? I guess I can take a quick look if it'd be fixed by optionally undoing that. But I fear gaps will then simply appear on the inside.

**Comment by ghost** [comment] 2024-11-12 16:57
Ok man, here it is, sorry for being late:

**Remastered HUD Interface**: https://www.mixmods.com.br/2021/02/vc-remastered-hud-interface-interface-em-hd/

I hope the issue is easy to fix and without any consequences

**Comment by CookiePLMonster** [comment] 2024-11-12 17:07
> I hope the issue is easy to fix and without any consequences

It's not a bug per se, rather the mod is created around the radar scaling incorrectly. But it may be possible to account for it with an INI option..

**Comment by ghost** [comment] 2024-11-13 06:00
Nice, so I hope the radar disc issue will become extremely less noticible or fixed all together.

**Comment by CookiePLMonster** [comment] 2024-11-18 18:27
@GTAGamingChannel44 I looked into this and it doesn't seem to be a SP bug, the radar disc texture is ruined by texture compression. I compared it in 4K, and the results are:

No SilentPatch:
![no-sp](https://github.com/user-attachments/assets/890fc27f-d60d-418a-b8c4-42fb28ab3500)

SilentPatch with a shrunk radar disc (current behaviour):
![sp-small](https://github.com/user-attachments/assets/4836726d-93ce-4cec-acf8-9fe696192b01)

SilentPatch without a shrunk radar disc (the option I planned to add):
![sp-big](https://github.com/user-attachments/assets/7322e01b-ca26-47a0-94fa-8716e37b550f)

The artifacts on the edges are identical on all three screenshots, which shows they are **not** the map textures bleeding through. And indeed, looking at a raw radar disc texture from this mod, you can easily see the miscolored edges when you zoom in:
![radardisc](https://github.com/user-attachments/assets/0a2611ec-97c1-4270-8358-6a532be56186)

Unless you meant something else and not those miscolorations on the disc edges, I am doing to close this issue as invalid.

**Comment by ghost** [comment] 2024-11-19 05:18
Dang it man, this UI mod is very faithful to the game (it's also recommended by a lot modders as a vanilla-friendly UI mod) and it's very sad that is has this big issue, but thank you so much for the heads up.

So it's turns out that the problem is not the SP's issue but rather the UI creator's mistake becuase this mod was built on non-4K or non-1440p resolutions. Can you tell me whether or not this radar issue is noticable with 4K resolutions or it will only be noticable if you actually looked at it very carefully?

**Comment by CookiePLMonster** [comment] 2024-11-19 07:11
> So it's turns out that the problem is not the SP's issue but rather the UI creator's mistake becuase this mod was built on non-4K or non-1440p resolutions. Can you tell me whether or not this radar issue is noticable with 4K resolutions or it will only be noticable if you actually looked at it very carefully?

The screenshots I made are in 4K so I'll let you judge that. It's not about the resolution but the texture compression, so it'll always look bad once you know what to look for.

**Closed as not planned by CookiePLMonster** 2024-11-19 07:11 UTC
Labels: invalid, gta vc
